services:
  mysql:
    image: mysql:8.3
    container_name: my-mysql-firstApp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FatemehMirarab
      MYSQL_DATABASE: mydb
      MYSQL_USER: fatemeh
      MYSQL_PASSWORD: Mirarab
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: go-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: fatemeh
      DB_PASSWORD: fatemeh
      DB_NAME: mydb
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

volumes:
  mysql_data: